課題１
azuma-takuya/FlutterStudy pull request #1
Opened 2023-04-14 07:22 UTC by azuma-takuya

100まで押せるボタンの実装しました。

2023-04-15 04:58 UTC, MinatoIshiwata requested changes
Pageはファイルを分けてください、またPage名は適宜つけてください。

2023-04-17 05:36 UTC, azuma-takuya commented
Page分けてみました。
確認お願いします。

2023-04-17 13:13 UTC, MinatoIshiwata commented on lib/CountUp.dart
ファイル名とクラス名合わせましょう。
ファイル名はsnakecaseにしてください🙋

2023-04-17 13:15 UTC, MinatoIshiwata commented on lib/CountUp.dart
> +  CountUpPage({Key? key, required this.title}) : super(key: key);
宣言方法少し古いかもです。
藤木さんのリポジトリみると良いです🙋

2023-04-17 13:15 UTC, MinatoIshiwata commented on lib/CountUp.dart
> +            ),
テンプレートなので消しましょう

2023-04-17 13:16 UTC, MinatoIshiwata commented on test/widget_test.dart
> +    await tester.pumpWidget(MyApp());
constを消した理由ありますでしょうか？🙋

2023-04-17 13:18 UTC, MinatoIshiwata requested changes
@azuma-takuya 
コメント複数つけました。
ご確認のほどよろしくお願いいたします。

2023-04-18 00:03 UTC, azuma-takuya commented on test/widget_test.dart
> +    await tester.pumpWidget(MyApp());
constがある場合赤いエラーが表示されてたので、
IDEAの補完機能でremove constの提案があり、そちらを実行したためです。
なぜエラーメッセージが出てたかなど理解はしてない状態です。

2023-04-18 00:16 UTC, azuma-takuya commented on lib/CountUp.dart
ファイル名とクラス名合わせました。
snakecaseにしました。

2023-04-18 01:14 UTC, MinatoIshiwata commented on test/widget_test.dart
> +    await tester.pumpWidget(MyApp());
const化についてはMeetで解説

2023-04-18 01:25 UTC, MinatoIshiwata approved these changes

2023-04-24 06:19 UTC, merged