To do list作成
azuma-takuya/FlutterStudy pull request #2
Opened 2023-04-17 07:08 UTC by azuma-takuya

まだ途中です。

2023-04-24 06:00 UTC, azuma-takuya commented
@MinatoIshiwata さん
機能の実装が終わったので、コードレビューお願いします。

2023-04-24 06:05 UTC, azuma-takuya commented
@MinatoIshiwata 
すいませんコンフリクト発生してて先にそちらの解決しようと思います。
次回からマージされたものから課題に取り組むようにします。

2023-04-24 18:48 UTC, MinatoIshiwata commented on lib/todolist_screen.dart
> +  const TodolistScreen({Key? key}) : super(key: key);
利用しているFlutterのバージョンが古いかもです。
もう少し短い書き方ができます🙋

2023-04-24 18:49 UTC, MinatoIshiwata commented on lib/todolist_screen.dart
> +                    );
メソッドにしてみましょう🙋

2023-04-24 18:50 UTC, MinatoIshiwata commented on lib/todolist_screen.dart
> +                    );
こちらも同じくです🙋

2023-04-24 18:50 UTC, MinatoIshiwata commented on lib/todolist_screen.dart
> +                    );
メソッドにしてみましょう

2023-04-24 18:51 UTC, MinatoIshiwata commented on lib/todolist_screen.dart
> +                      key: Key(_todos[index]),
Keyにも色々あるのですが、こちらが適切であるか一度考えてみましょう🙋

2023-04-24 18:52 UTC, MinatoIshiwata commented on lib/todolist_screen.dart
> +  final List<bool> _isEditing = [];
分けて管理する理由を教えて下さい🙋

2023-04-25 01:10 UTC, MinatoIshiwata commented on lib/todolist_screen.dart
> +  final List<bool> _isEditing = [];
JSONでまず考えてみましょう
パターン①
```
[
   {
      'value':  'ここで入力値を管理',
       'editing':  true,
   }
]
```

2023-04-25 01:11 UTC, MinatoIshiwata commented on lib/todolist_screen.dart
> +  final List<bool> _isEditing = [];
パターン②
```
{
   0: {
      'value':  'ここで入力値を管理',
       'editing':  true,
   }
}
```

2023-04-26 08:44 UTC, azuma-takuya commented on lib/todolist_screen.dart
> +  const TodolistScreen({Key? key}) : super(key: key);
修正しました。

2023-04-26 08:44 UTC, azuma-takuya commented on lib/todolist_screen.dart
> +                    );
メソッド化しました。

2023-04-26 08:45 UTC, azuma-takuya commented on lib/todolist_screen.dart
> +                    );
メソッド化しました。

2023-04-26 08:48 UTC, azuma-takuya commented on lib/todolist_screen.dart
> +                      key: Key(_todos[index]),
keyをFormの下に設定するように変更しました。

2023-04-26 08:58 UTC, azuma-takuya commented on lib/todolist_screen.dart
> +  final List<bool> _isEditing = [];
final List<bool> _isEditing = [];
を使って編集する考え方を変えて、ダイアログを呼び出して編集するような仕様に変更しました。
せっかくレビューして頂いたのに申し訳ありません。🙇
MAPとListを使用したやり方については、理解に時間がかかるため、
また別で進めたいと思ってます。

2023-04-26 08:59 UTC, azuma-takuya commented
メソッド化する際に元のソースでは結構苦労したため、
大きく使用を変えて実装を完了してる形になってます。
申し訳ありません🙇。

2023-04-26 19:30 UTC, MinatoIshiwata commented on lib/todolist_screen.dart
> +    _editController.text = _todos[index];
引数のvalueと何が違いますか？🤔

2023-04-26 19:31 UTC, MinatoIshiwata commented on lib/todolist_screen.dart
> +          children: [
TextFromFiledの階層まで下げてください

2023-04-26 19:32 UTC, MinatoIshiwata commented on lib/todolist_screen.dart
> +                  // 編集状態の場合、テキストフィールドを表示
_todos[index]をこちらで1度final宣言してはいかがでしょうか？
ご確認のほどよろしくお願いいたします。

2023-04-26 19:34 UTC, MinatoIshiwata requested changes
@azuma-takuya 
何点かコメントいたしました。
ご確認のほどよろしくお願いいたします。

2023-04-26 23:58 UTC, azuma-takuya commented on lib/todolist_screen.dart
> +    _editController.text = _todos[index];
valueと同じだったので、
_todos[index]をvalueに修正しました。

2023-04-27 00:53 UTC, azuma-takuya commented on lib/todolist_screen.dart
> +          children: [
Formの階層をColumnの下に配置しました。

2023-04-27 01:42 UTC, azuma-takuya commented on lib/todolist_screen.dart
> +          children: [
Formの階層をTextFromFiledの上に変えました。

2023-04-27 01:43 UTC, azuma-takuya commented on lib/todolist_screen.dart
> +                  // 編集状態の場合、テキストフィールドを表示
final宣言しました。

2023-04-27 01:59 UTC, azuma-takuya commented
@MinatoIshiwata 
ご指摘していただいた部分修正してプッシュしてます。
お時間空きましたら、確認お願いします。

2023-04-27 02:52 UTC, MinatoIshiwata approved these changes
LGTM🫐

#3 を進めてください🙋

2023-04-27 07:02 UTC, merged